#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


def load_manifest(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def resolve_gguf_file(manifest: dict) -> Path:
    gguf_file = manifest.get("exports", {}).get("gguf_file")
    if not gguf_file:
        raise RuntimeError(
            "The deployment manifest does not reference a GGUF export. Re-run the notebook with JEMMA_SAVE_GGUF=1 before preparing an Ollama bundle."
        )
    path = Path(gguf_file)
    if not path.is_file():
        raise RuntimeError(f"GGUF export not found: {path}")
    return path


def build_modelfile(model_name: str, gguf_filename: str, context_length: int | None) -> str:
    lines = [f"FROM ./{gguf_filename}"]
    if context_length:
        lines.append(f"PARAMETER num_ctx {context_length}")
    lines.append('TEMPLATE """{{ if .System }}<start_of_turn>system\\n{{ .System }}<end_of_turn>\\n{{ end }}{{ if .Prompt }}<start_of_turn>user\\n{{ .Prompt }}<end_of_turn>\\n<start_of_turn>model\\n{{ end }}"""')
    return "\n".join(lines) + "\n"


def build_entrypoint() -> str:
    return """#!/bin/sh
set -eu
export OLLAMA_HOST="0.0.0.0:${PORT:-8080}"
ollama serve &
server_pid=$!
cleanup() {
  kill "$server_pid"
}
trap cleanup INT TERM
attempt=0
until ollama list >/dev/null 2>&1; do
  attempt=$((attempt + 1))
  if [ "$attempt" -ge 60 ]; then
    echo "Ollama failed to start in time" >&2
    exit 1
  fi
  sleep 1
done
ollama create "${OLLAMA_MODEL_NAME}" -f /opt/jemma/Modelfile
wait "$server_pid"
"""


def build_dockerfile(gguf_filename: str, model_name: str) -> str:
    return f"""FROM ollama/ollama:latest
WORKDIR /opt/jemma
COPY {gguf_filename} /opt/jemma/{gguf_filename}
COPY Modelfile /opt/jemma/Modelfile
COPY entrypoint.sh /opt/jemma/entrypoint.sh
RUN chmod +x /opt/jemma/entrypoint.sh
ENV OLLAMA_MODEL_NAME={model_name}
EXPOSE 8080
ENTRYPOINT ["/opt/jemma/entrypoint.sh"]
"""


def build_deploy_script(model_name: str) -> str:
    return f"""param(
    [string]$ProjectId,
    [string]$Region = "us-central1",
    [string]$ServiceName = "{model_name}"
)

if (-not $ProjectId) {{
    throw "ProjectId is required."
}}

gcloud run deploy $ServiceName `
  --source . `
  --project $ProjectId `
  --region $Region `
  --allow-unauthenticated `
  --cpu 8 `
  --memory 32Gi `
  --timeout 900 `
  --set-env-vars OLLAMA_MODEL_NAME={model_name}
"""


def create_bundle(manifest_path: Path, output_dir: Path | None = None) -> Path:
    manifest = load_manifest(manifest_path)
    gguf_file = resolve_gguf_file(manifest)
    model_name = str(manifest.get("artifact_slug") or gguf_file.stem)
    bundle_root = output_dir or (manifest_path.parent / f"{model_name}-cloud-run-bundle")
    bundle_root.mkdir(parents=True, exist_ok=True)

    bundle_gguf = bundle_root / gguf_file.name
    shutil.copy2(gguf_file, bundle_gguf)

    modelfile_path = bundle_root / "Modelfile"
    modelfile_path.write_text(
        build_modelfile(model_name, gguf_file.name, manifest.get("max_seq_length")),
        encoding="utf-8",
    )
    entrypoint_path = bundle_root / "entrypoint.sh"
    entrypoint_path.write_text(build_entrypoint(), encoding="utf-8")
    dockerfile_path = bundle_root / "Dockerfile"
    dockerfile_path.write_text(build_dockerfile(gguf_file.name, model_name), encoding="utf-8")
    deploy_path = bundle_root / "deploy-cloud-run.ps1"
    deploy_path.write_text(build_deploy_script(model_name), encoding="utf-8")

    bundle_manifest = {
        "source_manifest": str(manifest_path),
        "artifact_slug": model_name,
        "gguf_file": str(bundle_gguf),
        "recommended_service_name": model_name,
        "files": {
            "Dockerfile": str(dockerfile_path),
            "Modelfile": str(modelfile_path),
            "entrypoint.sh": str(entrypoint_path),
            "deploy-cloud-run.ps1": str(deploy_path),
        },
    }
    (bundle_root / "bundle-manifest.json").write_text(json.dumps(bundle_manifest, indent=2), encoding="utf-8")
    return bundle_root


def main() -> int:
    parser = argparse.ArgumentParser(description="Prepare an Ollama + Google Cloud deployment bundle from a notebook export manifest.")
    parser.add_argument("manifest", type=Path, help="Path to the deployment manifest generated by toolbox/run_notebook_cells.py")
    parser.add_argument("--output-dir", type=Path, help="Optional output directory for the generated bundle")
    args = parser.parse_args()
    bundle_root = create_bundle(args.manifest, args.output_dir)
    print(json.dumps({"bundle_root": str(bundle_root)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
