import subprocess
subprocess.run('wmic cpu get name > cpu.txt 2>&1', shell=True)
subprocess.run('wmic os get TotalVisibleMemorySize > ram.txt 2>&1', shell=True)  
subprocess.run('wmic path win32_videocontroller get name > gpu.txt 2>&1', shell=True)
subprocess.run('wmic logicaldisk get name,size,freespace > disks.txt 2>&1', shell=True)
subprocess.run('netsh interface ipv4 show interfaces > net_int.txt 2>&1', shell=True)
subprocess.run('wmic nic get name,speed,status > nic.txt 2>&1', shell=True)
subprocess.run('where java > java.txt 2>&1', shell=True)
subprocess.run('where adb > adb.txt 2>&1', shell=True)
subprocess.run('where tailscale > tailscale.txt 2>&1', shell=True)
subprocess.run('where gradle > gradle.txt 2>&1', shell=True)
subprocess.run('where speedtest > speedtest.txt 2>&1', shell=True)
print("All commands executed. Check output files in current directory.")
