[hue]
app_key = "set-in-HUE_APP_KEY-env-var"

[smartplug]
api_key = "set-in-SMARTPLUG_API_KEY-env-var"

[discord]
client_id = "set-in-DISCORD_CLIENT_ID-env-var"
public_key = "set-in-DISCORD_PUBLIC_KEY-env-var"
guild_id = "set-in-DISCORD_GUILD_ID-env-var"
bot_token = "set-in-DISCORD_BOT_TOKEN-env-var"
client_secret = "set-in-DISCORD_CLIENT_SECRET-env-var"
